spring:
  datasource:
    url: jdbc:mysql://localhost:3306/casa-do-codigo?serverTimezone=UTC
    username: eduardo
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
